name: blinkit
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: 2.4.4

flutter_native_splash:
  color: "#F7CB45"
  image: assets/blinkit_logo.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#F7CB45"
    image: assets/blinkit_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
